/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegolaberinto;

import java.applet.AudioClip;
import java.awt.Color;

/**
 *
 * @author blackeagle
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        this.getContentPane().setBackground(Color.orange);
        this.setLocationRelativeTo(null);
        
        AudioClip sonido;
        sonido = java.applet.Applet.newAudioClip(getClass().getResource(""));
        sonido.stop();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        game3 = new javax.swing.JButton();
        game1 = new javax.swing.JButton();
        game2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        game3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        game3.setBorderPainted(false);
        game3.setContentAreaFilled(false);
        game3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play2.png"))); // NOI18N
        game3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game3ActionPerformed(evt);
            }
        });
        getContentPane().add(game3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 170, 140));

        game1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        game1.setBorderPainted(false);
        game1.setContentAreaFilled(false);
        game1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play2.png"))); // NOI18N
        game1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game1ActionPerformed(evt);
            }
        });
        getContentPane().add(game1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 150, 140));

        game2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play.png"))); // NOI18N
        game2.setBorderPainted(false);
        game2.setContentAreaFilled(false);
        game2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/play2.png"))); // NOI18N
        game2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                game2ActionPerformed(evt);
            }
        });
        getContentPane().add(game2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 160, 140));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Nivel 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setText("Nivel 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setText("Nivel 3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, -1, -1));

        back.setBackground(new java.awt.Color(51, 153, 255));
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void game2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game2ActionPerformed
        // TODO add your handling code here:
        
        juego ob = new juego();
        
        dispose(); 
        
        ob.setVisible(true);
            
        
        
        
    }//GEN-LAST:event_game2ActionPerformed

    private void game1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game1ActionPerformed
        // TODO add your handling code here:
        
        juego2 ob = new juego2();
        
        
        dispose(); 
        
        ob.setVisible(true);
            
        
        
        
        
    }//GEN-LAST:event_game1ActionPerformed

    private void game3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_game3ActionPerformed
        // TODO add your handling code here:
        
        juego3 ob = new juego3();
        
        
        dispose(); 
        
        ob.setVisible(true);
            
        
        
    }//GEN-LAST:event_game3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton game1;
    private javax.swing.JButton game2;
    private javax.swing.JButton game3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
